### ISSUE TITLE
MetadataException....

### ISSUE THREAD

**Issue by MHacker9404** [Dixin/EntityFramework.Functions#19]
Getting this exception: System.Data.Entity.Core.MetadataException: Schema specified is not valid. Errors: 
(0,0) : error 0005: The 'Aggregate' attribute is not allowed.
(0,0) : error 0005: The 'BuiltIn' attribute is not allowed.
(0,0) : error 0005: The 'NiladicFunction' attribute is not allowed.
(0,0) : error 0005: The 'IsComposable' attribute is not allowed.
(0,0) : error 0005: The 'ParameterTypeSemantics' attribute is not allowed.
(0,0) : error 0005: The 'Schema' attribute is not allowed.
(0,0) : error 0005: The 'Mode' attribute is not allowed.

Here is the ModelDefinedFunction that I created and attached to the context:
`public static class ModelDefinedFunctions
    {
        [ModelDefinedFunction(nameof(ParseDecimal), "Envoy.Infrastructure.Data.SqlServer.dbEnvoy", @"cast(svalue as Decimal(20,8))")]
        public static decimal ParseDecimal(this string svalue) => decimal.Parse(svalue);
    }`

**Comment by Dixin** [comment]
I have added an example for `cast`. See 8c0ea5a5a80b32a00471515790728ce3e32c30a9.
