### ISSUE TITLE
Can I add a "function" which acts like "LIKE"?

### ISSUE THREAD

**Issue by springy76** [Dixin/EntityFramework.Functions#20]
SQLite's full text search uses a custom keyword "MATCH" which acts like "LIKE".

Can any of the existing functions create custom SQL which takes a single parameter as input and will create SQL like `WHERE ColumnName MATCH @p0`?

Would be used like so: `context.MySet.Where(row => CustomFunctions.Match(row.ColumnName, "string expression which should go to @p0") )`

**Comment by Dixin** [comment]
No. This is not supported by EF, because MATCH/LIKE is not a function, it cannot be used as LIKE(expression, pattern).

For LIKE, it can be replaced by PATINDEX(pattern, expression) function call.
