### ISSUE TITLE
How to use BuiltInFunction with Cast or Convert 

### ISSUE THREAD

**Issue by kcjhendriks** [Dixin/EntityFramework.Functions#21]
How Does one setup the build in function to support the build in cast or conver functions?
[msdn link](https://msdn.microsoft.com/en-us/library/ms187928.aspx)

So far I have this

`        [Function(FunctionType.BuiltInFunction, "CAST")]
        public static double Cast(string value) => Function.CallNotSupported<double>();`

`            modelBuilder.Conventions.Add(new FunctionConvention<VProCressContext>());
            modelBuilder.AddFunctions(typeof(MySQLFunctions));`

But I do not know how to supply the type that is needed with the cast

**Comment by Dixin** [comment]
I have added an example for `cast`. Please see 8c0ea5a5a80b32a00471515790728ce3e32c30a9.
