### ISSUE TITLE
Model-defined functions

### ISSUE THREAD

**Issue by SteveRuble** [Dixin/EntityFramework.Functions#3]
I figured out a way to implement model-defined functions, so you can write something like this:

```
[ModelDefinedFunction(nameof(FormatName), "EntityFramework.Functions.Tests.Examples",
@"CASE 
    WHEN person.Title IS NOT NULL THEN person.Title + ' ' 
    ELSE ''
  END + person.FirstName + ' ' + person.LastName"
)]
public static string FormatName(this Person person) => 
                                 string.Format("{0}{1} {2}",
							                   person.Title == null ? "" : person.Title + " ",
                                               person.FirstName,
                                               person.LastName);
 ```      

If you call the method in a LINQ query, it gets translated to SQL, but if you call it on an actual instance of `Person` it executes the method. (Or you could have the implementation throw if you only want the function to work on the SQL side, of course.)

Would you be interested in a pull request for this?

**Comment by Dixin** [comment]
Absolutely. This is cool.
