### ISSUE TITLE
Support for Entity Framework 6.3/6.4 on .Net Standard 2.1

### ISSUE THREAD

**Issue by fedarovich** [Dixin/EntityFramework.Functions#38]
Could you please add support for Entity Framework 6.3/6.4 on .Net Standard 2.1 targets?

If you don't have time, I can probably do it myself and create a pull request.

**Comment by Dixin** [comment]
Done with d9f80b302bdc9a74e14911326109bb200a151b1d, fe6c3df2097a5815e72e4e6aaa0ad7c7b292d1e0, 518283529d3adb8e2a220b8b2001ef205c2205a2. Please update your NuGet package.
